package com.regrx.serena.common.constant;

public enum StrategyEnum {
    STRATEGY_NULL,
    STRATEGY_MA_520,
    STRATEGY_LOSS_LIMIT,
    STRATEGY_PROFIT_LIMIT,
    STRATEGY_FILL_GAP,
    STRATEGY_MA_240,
    STRATEGY_MA_240_520,
    STRATEGY_BASIC_EMA_FOR_UP,
    STRATEGY_BASIC_EMA_FOR_DOWN,
    STRATEGY_EMA_520,
    STRATEGY_BOLLINGER,
    STRATEGY_DONCHIAN_GOLDEN,

    STRATEGY_CLOSE_ON_END,
    STRATEGY_REOPEN,
    STRATEGY_ONLY_ONE_PER_DAY,
    STRATEGY_FIND_MAX_PERCENT,
    STRATEGY_FIND_MAX_PERCENT_REVERSE,
}
